# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

Email: <%= Figaro.env.Username %>
Password: <%= Figaro.env.Password %>

Facebook_app_key: <%= Figaro.env.Facebook_app_key %>
Facebook_app_secret: <%= Figaro.env.Facebook_app_secret %>

Google_app_key: <%= Figaro.env.Google_app_key %>
Google_app_secret: <%= Figaro.env.Google_app_secret %>


Api_Movie: <%= Figaro.env.Api_Movie %>




development:
  secret_key_base: c61bc89b4cfa4a2fafc10be2dba0cab0f98c0536b73c1cd9c8e039dd00e592f68b2dd6fd3d1f03b6fe1a06e721dddc92704a0ac24f7d667268ceb264b4a15367
  Automatic_Api: <%= ENV["Automatic_Api"] %>
  Create_Path: <%=ENV["Create_Path"]%>

test:
  secret_key_base: fb3d4a82d53f786ea51ddda8a852d6498a91ce0b42313c689b006bd5a68476fcada5bd5b8fec83c477b844b2d88b9ffdb8a9a9350627fc48490c4c828bffd17d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  Automatic_Api: <%=ENV["Automatic_Api"]%>
  Create_Path: <%=ENV["Create_Path"]%>
