# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Movie.create(title: "The Pursuit of Happyness",year: "2006",genre: "Biography",cast: "Will Smith, Jaden Smith, Thandie Newton, Brian Howe",plot: "In 1981, San Francisco salesman Chris Gardner invests his entire life savings in portable bone density scanners, which he demonstrates to doctors and pitches as a handy quantum leap over standard X-rays. The scanners play a vital role in Chris' life. While he is able to sell most of them, the time lag between the sales and his growing financial demands enrage his already bitter and alienated wife Linda, who works as a hotel maid. The financial instability increasingly erodes their marriage, in spite of them caring for Christopher Jr., their soon-to-be five-year-old son.",remote_image_url: "https://d33x6c2gojonez.cloudfront.net/wp-content/uploads/sites/1076/2015/09/01060438/5-lessons-i-learned-from-the-pursuit-of-happyness.jpg",rating: "8.0",web: "http://www.sonypictures.com/movies/thepursuitofhappyness/")

Movie.create(title: "Guardians of the Galaxy Vol. 2",year: "2017",genre: "Action",cast: "Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel",plot: "Peter Quill and his fellow Guardians are hired by a powerful alien race, the Sovereign, to protect their precious batteries from invaders. When it is discovered that Rocket has stolen the items they were sent to guard, the Sovereign dispatch their armada to search for vengeance. As the Guardians try to escape, the mystery of Peter's parentage is revealed.",remote_image_url: "https://fsmedia.imgix.net/3d/de/72/cd/83d5/4a38/85b0/358e5e0740ab/guardians-of-the-galaxy-vol-2.jpeg",rating: "7.8",web: "https://marvel.com/guardians")

Movie.create(title: "Man of Steel",year: "2013",genre: "Sci-fiction",cast: "Henry Cavill,Amy Adams,Michael Shannon,Kevin Costner,Diane Lane",plot: "With Krypton destabilized from mining of the planet's core, Jor-El, chief advisor to Krypton's supreme council, recommends the council give him control of the genetics codex. Before any action can be taken, soldiers led by General Zod, an old friend of Jor-El's, launch an uprising and arrest the councilors. Realising that Krypton is doomed, Jor-El steals the genetic codex sought by Zod and infuses them into the DNA of his infant son, Kal-El – the first naturally born Kryptonian child in centuries.", remote_image_url: "https://wallpapercave.com/wp/wGChWSd.jpg",rating: "8.1",web: "https://www.warnerbros.com/man-steel")

Movie.create(title: "Interstellar",year: "2014",genre: "Action",cast: "Keanu Reeves, Michael Nyqvist, Alfie Allen, Willem Dafoe",plot: "An ex-hitman comes out of retirement to track down the gangsters that took everything from him.",remote_image_url: "https://s-media-cache-ak0.pinimg.com/originals/28/53/92/285392f81b121c24ec9846eb0ed97177.jpg",rating: "7.3",web: "http://johnwickthemovie.com/")
Movie.create(title: "Sky Fall",year: "2014",genre: "Action",cast: "Keanu Reeves, Michael Nyqvist, Alfie Allen, Willem Dafoe",plot: "An ex-hitman comes out of retirement to track down the gangsters that took everything from him.",remote_image_url: "https://images7.alphacoders.com/550/550739.jpg",rating: "7.3",web: "http://johnwickthemovie.com/")
Movie.create(title: "Batman Vs Superman",year: "2016",genre: "Sci-fiction",cast: "Keanu Reeves, Michael Nyqvist, Alfie Allen, Willem Dafoe",plot: "An ex-hitman comes out of retirement to track down the gangsters that took everything from him.",remote_image_url: "http://redcarpetrefs.com/wp-content/uploads/2016/03/z1-5.jpg",rating: "7.3",web: "http://johnwickthemovie.com/")


Movie.create(title: "John Wick Chapter 2: Wick-vizzed",year: "2017",genre: "Action",cast: "J.J. Perry, Keanu Reeves, Ruby Rose, Chad Stahelski",plot: "A candid look at rehearsal footage in support of a focus on pre-viz. A man is picked up by a fishing boat, bullet-riddled and suffering from amnesia, before racing to elude assassins and regain his memory. A man is picked up by a fishing boat, bullet-riddled and suffering from amnesia, before racing to elude assassins and regain his memory.",remote_image_url: "http://bestscreenwallpaper.pro/wp-content/uploads/2016/05/John-Wick-Chapter-Two-Movie-wallpaper-HD-2017.jpg",rating: "8.1",web: "http://johnwickthemovie.com/")

Movie.create(title: "The Bourne Identity",year: "2002",genre: "Action",cast: "Matt Damon, Franka Potente, Chris Cooper, Clive Owen",plot: "A man is picked up by a fishing boat, bullet-riddled and suffering from amnesia, before racing to elude assassins and regain his memory.A man is picked up by a fishing boat, bullet-riddled and suffering from amnesia, before racing to elude assassins and regain his memory.A man is picked up by a fishing boat, bullet-riddled and suffering from amnesia, before racing to elude assassins and regain his memory.A man is picked up by a fishing boat, bullet-riddled and suffering from amnesia, before racing to elude assassins and regain his memory.A man is picked up by a fishing boat, bullet-riddled and suffering from amnesia, before racing to elude assassins and regain his memory.",remote_image_url: "http://inspirationally.net/bourne/identity/extra/posters/identity03.jpg",rating: "7.9",web: "http://www.thebourneidentity.com/")


# AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?



Movie.create(title: "BlackPanther",year: "2018",genre: "Action",cast: "Matt Damon, Franka Potente, Brian Cox, Julia Stiles",plot: "When Jason Bourne is framed for a CIA operation gone awry, he is forced to resume his former life as a trained assassin to survive.",remote_image_url: "https://www.hdwallpapers.site/previews/the-black-panther-2018-movie-poster-77.jpg",rating: "7.9",web: "http://www.thebournesupremacy.com/")
Movie.create(title: "Deadpool",year: "2016",genre: "Action",cast: "Matt Damon, Franka Potente, Brian Cox, Julia Stiles",plot: "When Jason Bourne is framed for a CIA operation gone awry, he is forced to resume his former life as a trained assassin to survive.",remote_image_url: "https://farm4.staticflickr.com/3699/18958720124_7d10cb12fa_b.jpg",rating: "8.8",web: "http://www.thebournesupremacy.com/")

Movie.create(title: "Oblivion",year: "2015",genre: "Action",cast: "Matt Damon, Franka Potente, Brian Cox, Julia Stiles",plot: "When Jason Bourne is framed for a CIA operation gone awry, he is forced to resume his former life as a trained assassin to survive.When Jason Bourne is framed for a CIA operation gone awry, he is forced to resume his former life as a trained assassin to survive.When Jason Bourne is framed for a CIA operation gone awry, he is forced to resume his former life as a trained assassin to survive.When Jason Bourne is framed for a CIA operation gone awry, he is forced to resume his former life as a trained assassin to survive.",remote_image_url: "https://d2kektcjb0ajja.cloudfront.net/images/posts/feature_images/000/000/072/large-1466557422-feature.jpg?1466557422",rating: "9.2",web: "http://www.thebournesupremacy.com/")

Movie.create(title: "SpiderMan-HomeComing",year: "2004",genre: "Action",cast: "Matt Damon, Franka Potente, Brian Cox, Julia Stiles",plot: "When Jason Bourne is framed for a CIA operation gone awry, he is forced to resume his former life as a trained assassin to survive.",remote_image_url: "https://pre00.deviantart.net/fe84/th/pre/i/2017/018/5/5/spider_man_homecoming_poster__2017__by_nomada_warrior-davwt5l.jpg",rating: "7.8",web: "http://www.thebournesupremacy.com/")
Movie.create(title: "The Fault In Our Stars",year: "2004",genre: "Action",cast: "Matt Damon, Franka Potente, Brian Cox, Julia Stiles",plot: "When Jason Bourne is framed for a CIA operation gone awry, he is forced to resume his former life as a trained assassin to survive.",remote_image_url: "https://wallpapercave.com/wp/wp1910519.jpg",rating: "7.8",web: "http://www.thebournesupremacy.com/")
# User.create(email: 'office.vansh@gmail.com', password: '123456', password_confirmation: '123456') if Rails.env.development?
